### ISSUE TITLE
private method __reset doesn't exist in MWCP Reporter class

### ISSUE THREAD

**Issue by 0xd0cf11e** [CybercentreCanada/assemblyline-service-configextractor#20]
The service complains when it tries to access this:
https://github.com/CybercentreCanada/assemblyline-service-configextractor/blob/4875874f17a5459b51104484da7aa5f959f8a4c3/configextractor.py#L83

Error:
```
  File "/opt/al_service/configextractor.py", line 83, in execute
    self.mwcp_reporter._Reporter__reset()
AttributeError: 'Runner' object has no attribute '_Reporter__reset'
```

According to the recent Changelog (https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/3.3.0/CHANGELOG.md), the class `Reporter` is not replaced by `Runner` and `Runner` does not have a private method `__reset()` created.

**Comment by cccs-aa** [comment]
Hello,
Yes this and other issues will be fixed in the upcoming release of configextractor. Stay tuned!
Thanks

**Comment by 0xd0cf11e** [comment]
thankyou! :)
