### ISSUE TITLE
Feature Request: Ability to use Signature sources to update ConfigExtractor rules

### ISSUE THREAD

**Issue by scottpas** [CybercentreCanada/assemblyline-service-configextractor#42]
A mechanism to provide a git repo with the structure of the [ConfigExtractor dependencies folder](https://github.com/CybercentreCanada/configextractor-py/tree/main/dependencies) as a signature source would be extremely useful, so that any time a change is made it's reflected in the ConfigExtractor service. This would be similar to how Yara/Sigma/Suricata signatures are configured to pull from their respective sources.

**Comment by cccs-rs** [comment]
Hey @scottpas, we're currently looking at this possibility and it may involve a major change like (4.3?).

I've created a ticket for this request and will update on the progress of this.
